INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID)
VALUES (1, 'test set 1', 1);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID)
VALUES (1, 'test set 1', 2);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID)
VALUES (1, 'test set 1', 3);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID)
VALUES (1, 'test set 1', 4);

INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID)
VALUES (1, 'test set 1', 5);


INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID) VALUES (3, 'test set 3', 9);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID) VALUES (3, 'test set 3', 10);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID) VALUES (3, 'test set 3', 11);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID) VALUES (3, 'test set 3', 12);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID) VALUES (3, 'test set 3', 13);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID) VALUES (3, 'test set 3', 14);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID) VALUES (3, 'test set 3', 15);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID) VALUES (3, 'test set 3', 16);