DELETE FROM PHASE;
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8185);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8030);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 5621);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8370);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8492);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8190);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8080);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 5833);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 1710);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 4660);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8470);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8200);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8490);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8186);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8170);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 4668);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 4659);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8499);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 7502);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 5825);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 4670);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8180);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8400);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 7405);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'IAP_TYPE', 'HA_PV', 8163);

INSERT INTO PHASE VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'DEVO_TYPE', 'HA_PV', 55.2);
INSERT INTO PHASE VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'DEVO_TYPE', 'HA_PV', 49.2);
INSERT INTO PHASE VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'DEVO_TYPE', 'HA_PV', 36.5);
INSERT INTO PHASE VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'DEVO_TYPE', 'HA_PV', 36.2);
INSERT INTO PHASE VALUES (1, 'High Arousal - Positive Valence', 'Fase 1', 'DEVO_TYPE', 'HA_PV', 28.1);

INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2340);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 1440);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2040);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 5830);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2050);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2080);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2070);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 1460);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 5210);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 1750);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2154);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2260);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2550);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 7200);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2057);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 1920);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 5829);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2660);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2091);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 1441);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 7492);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2165);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 1463);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 2398);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (2, 'Low Arousal - Positive Valence', 'Fase 2', 'IAP_TYPE', 'LA_PV', 5982);

INSERT INTO PHASE VALUES (2, 'Low Arousal - Positive Valence' ,'Fase 2', 'DEVO_TYPE', 'LA_PV', 102.2);
INSERT INTO PHASE VALUES (2, 'Low Arousal - Positive Valence' ,'Fase 2', 'DEVO_TYPE', 'LA_PV', 70.5);
INSERT INTO PHASE VALUES (2, 'Low Arousal - Positive Valence' ,'Fase 2', 'DEVO_TYPE', 'LA_PV', 29.2);
INSERT INTO PHASE VALUES (2, 'Low Arousal - Positive Valence' ,'Fase 2', 'DEVO_TYPE', 'LA_PV', 21.3);
INSERT INTO PHASE VALUES (2, 'Low Arousal - Positive Valence' ,'Fase 2', 'DEVO_TYPE', 'LA_PV', 9.7);

INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 8466);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 7476);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 9468);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 2309);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 5970);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 1945);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 6000);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 1505);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 2810);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 9171);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 9926);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 1280);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 1230);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 2795);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 9182);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 7037);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 2446);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 1270);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 2695);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 9584);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 9186);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 9080);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 9404);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 7520);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (3, 'Low Arousal - Negative Valence', 'Fase 3', 'IAP_TYPE', 'LA_NV', 2520);


INSERT INTO PHASE VALUES (3 ,'Low Arousal - Negative Valence' ,'Fase 3' ,'DEVO_TYPE' ,'LA_NV', 135.2);
INSERT INTO PHASE VALUES (3 ,'Low Arousal - Negative Valence' ,'Fase 3' ,'DEVO_TYPE' ,'LA_NV', 117.2);
INSERT INTO PHASE VALUES (3 ,'Low Arousal - Negative Valence' ,'Fase 3' ,'DEVO_TYPE' ,'LA_NV', 76.1);
INSERT INTO PHASE VALUES (3 ,'Low Arousal - Negative Valence' ,'Fase 3' ,'DEVO_TYPE' ,'LA_NV', 64.3 );
INSERT INTO PHASE VALUES (3 ,'Low Arousal - Negative Valence' ,'Fase 3' ,'DEVO_TYPE' ,'LA_NV', 47.2);

INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 8475);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 1321);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 1120);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 1931);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 1726);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 6230);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 1050);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 1300);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 6550);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 1310);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 6350);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 1932);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 3000);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 3010);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 1930);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 6510);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 6900);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 1303);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 6260);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 9940);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 3500);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 1302);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 8480);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 1201);
INSERT INTO [dbo].[PHASE] (ID, DESCRIPTION, NAME, STIMULI_TYPE, VALENCE_AROUSAL_QUARDRANT, STIMULI_ID)
VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'IAP_TYPE', 'HA_NV', 6231);

INSERT INTO PHASE VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'DEVO_TYPE', 'HA_NV', 122.1);
INSERT INTO PHASE VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'DEVO_TYPE', 'HA_NV', 114.2);
INSERT INTO PHASE VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'DEVO_TYPE', 'HA_NV', 95.1);
INSERT INTO PHASE VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'DEVO_TYPE', 'HA_NV', 66.3);
INSERT INTO PHASE VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'DEVO_TYPE', 'HA_NV', 93.3);
INSERT INTO PHASE VALUES (4, 'High Arousal - Negative Valence', 'Fase 4', 'DEVO_TYPE', 'HA_NV', 91.1);