drop table [dbo].[PHASE];
CREATE TABLE PHASE (
  ID							INT						NOT NULL,
  DESCRIPTION					VARCHAR(100),
  NAME							VARCHAR(100), 
  PHASE_TYPE					VARCHAR(100)			NOT NULL, 
  VALENCE_AROUSAL_QUARDRANT		VARCHAR(100)			NOT NULL,
  STIMULI_ID					float					NOT NULL,
);
