INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID)
VALUES (2, 'test set 2', 5);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID)
VALUES (2, 'test set 2', 6);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID)
VALUES (2, 'test set 2', 7);
INSERT INTO [dbo].[TEST_SET] (ID, DESCRIPTION, PHASE_ID)
VALUES (2, 'test set 2', 8);